version: '3'

# Use this file to specify configurations that will be common for
# both local and production environments

services:
  # TODO: Figure out how to have this locally
  # traefik:
  #   build:
  #     context: .
  #     dockerfile: ./compose/production/traefik/Dockerfile
  #   image: itinerar_traefik
  #   depends_on:
  #     - django

  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: itinerar_django
    container_name: itinerar_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
    # TODO: Fix this
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  docs:
    image: itinerar_docs
    container_name: itinerar_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    ports:
      - "7001:7000"
    command: /start-docs

  celeryworker:
    <<: *django
    image: itinerar_celeryworker
    container_name: itinerar_celeryworker
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: itinerar_celerybeat
    container_name: itinerar_celerybeat
    ports: []
    command: /start-celerybeat

  # TODO: Figure out what this is all about
  flower:
    <<: *django
    image: itinerar_flower
    container_name: itinerar_flower
    ports:
      - "5555:5555"
    command: /start-flower
